version: '2'

services:
    python_server:

        restart: always
        mem_limit: 100m
        logging:
            options:
                "max-size": 500m
        build:
            dockerfile: dockerfile
            context: ./
        entrypoint:
            python api.py
        environment:
            - MAIL_USERNAME
            - MAIL_PASSWORD
            - RECIPIENTS

        ports:
            - '5000:5000'
